-- Generated by monitoring/scripts/split_seed_dump.py
-- v-platform-portal app baseline seeds (menu_items / grants / overrides scoped to this app).
-- Idempotent: ON CONFLICT DO NOTHING on all inserts.

SET client_encoding = 'UTF8';

BEGIN;

INSERT INTO public.menu_items (id, permission_key, label, icon, path, menu_type, iframe_url, iframe_fullscreen, open_in_new_tab, parent_key, sort_order, section, app_id, is_active, created_by, updated_by, created_at, updated_at) VALUES (2340, 'portal_home', '포털 홈', 'LayoutDashboard', '/', 'built_in', NULL, NULL, NULL, NULL, 100, 'basic', 'v-platform-portal', true, NULL, NULL, '2026-04-19 12:59:30.447847+00', '2026-04-19 12:59:30.447847+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.menu_items (id, permission_key, label, icon, path, menu_type, iframe_url, iframe_fullscreen, open_in_new_tab, parent_key, sort_order, section, app_id, is_active, created_by, updated_by, created_at, updated_at) VALUES (2341, 'portal_help', '도움말', 'HelpCircle', '/help', 'built_in', NULL, NULL, NULL, NULL, 700, 'basic', 'v-platform-portal', true, NULL, NULL, '2026-04-19 12:59:30.447847+00', '2026-04-19 12:59:30.447847+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.menu_items (id, permission_key, label, icon, path, menu_type, iframe_url, iframe_fullscreen, open_in_new_tab, parent_key, sort_order, section, app_id, is_active, created_by, updated_by, created_at, updated_at) VALUES (553, 'app_management', '앱 관리', 'Box', '/admin/apps', 'built_in', NULL, NULL, false, NULL, 1500, 'admin', 'v-platform-portal', true, NULL, NULL, '2026-04-12 15:34:26.142848+00', '2026-04-12 15:34:26.142848+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.notification_app_overrides (id, notification_id, app_id, is_active, updated_at) VALUES (1, 4, 'v-platform-portal', false, '2026-04-12 10:38:56.687034+00') ON CONFLICT (notification_id, app_id) DO NOTHING;
INSERT INTO public.portal_apps (id, app_id, display_name, description, icon, frontend_url, api_url, health_endpoint, sort_order, is_active, created_by, updated_by, created_at, updated_at) VALUES (1, 'v-channel-bridge', 'Channel Bridge', 'Slack ↔ Teams 메시지 브리지', 'MessageSquare', 'http://192.168.1.216:5173', 'http://v-project-bridge-backend:8000', '/api/health', 0, true, NULL, 5, '2026-04-12 15:21:44.624831+00', '2026-04-15 02:21:09.326125+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.portal_apps (id, app_id, display_name, description, icon, frontend_url, api_url, health_endpoint, sort_order, is_active, created_by, updated_by, created_at, updated_at) VALUES (2, 'v-platform-template', 'Platform Template', '플랫폼 템플릿 앱', 'LayoutDashboard', 'http://192.168.1.216:5174', 'http://v-project-template-backend:8000', '/api/health', 10, true, NULL, 5, '2026-04-12 15:21:44.624846+00', '2026-04-15 02:21:27.410827+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.portal_apps (id, app_id, display_name, description, icon, frontend_url, api_url, health_endpoint, sort_order, is_active, created_by, updated_by, created_at, updated_at) VALUES (4, 'v-ui-builder', 'AI UI Builder', 'AI 기반의 UI Builder', 'Box', 'http://192.168.1.216:5181', 'http://v-ui-builder-backend:8000', '/api/health', 0, true, 5, 5, '2026-04-19 13:48:05.612377+00', '2026-04-19 13:50:30.68813+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.portal_apps (id, app_id, display_name, description, icon, frontend_url, api_url, health_endpoint, sort_order, is_active, created_by, updated_by, created_at, updated_at) VALUES (5, 'v-itsm', 'ITSM', 'ITSM', 'route', 'http://192.168.1.216:5182', 'http://itsm-backend:8000', '/api/health', 0, true, 5, 5, '2026-04-22 01:07:25.60422+00', '2026-04-22 01:07:25.604307+00') ON CONFLICT (id) DO NOTHING;

SELECT setval('public.menu_items_id_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM public.menu_items), false);
SELECT setval('public.permission_group_grants_id_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM public.permission_group_grants), false);
SELECT setval('public.notification_app_overrides_id_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM public.notification_app_overrides), false);
SELECT setval('public.portal_apps_id_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM public.portal_apps), false);

COMMIT;
