-- Generated by monitoring/scripts/split_seed_dump.py
-- v-platform-template app baseline seeds (menu_items / grants / overrides scoped to this app).
-- Idempotent: ON CONFLICT DO NOTHING on all inserts.

SET client_encoding = 'UTF8';

BEGIN;

INSERT INTO public.menu_items (id, permission_key, label, icon, path, menu_type, iframe_url, iframe_fullscreen, open_in_new_tab, parent_key, sort_order, section, app_id, is_active, created_by, updated_by, created_at, updated_at) VALUES (2339, 'dashboard', '대시보드', 'LayoutDashboard', '/', 'built_in', NULL, NULL, NULL, NULL, 100, 'basic', 'v-platform-template', true, NULL, NULL, '2026-04-19 12:59:30.446987+00', '2026-04-19 12:59:30.446987+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.menu_items (id, permission_key, label, icon, path, menu_type, iframe_url, iframe_fullscreen, open_in_new_tab, parent_key, sort_order, section, app_id, is_active, created_by, updated_by, created_at, updated_at) VALUES (2342, 'help', '도움말', 'HelpCircle', '/help', 'built_in', NULL, NULL, NULL, NULL, 700, 'basic', 'v-platform-template', true, NULL, NULL, '2026-04-19 12:59:30.446987+00', '2026-04-19 12:59:30.446987+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.menu_items (id, permission_key, label, icon, path, menu_type, iframe_url, iframe_fullscreen, open_in_new_tab, parent_key, sort_order, section, app_id, is_active, created_by, updated_by, created_at, updated_at) VALUES (214, 'custom_menu_test01', '커스텀 메뉴 01', NULL, '/custom/menu/test01', 'custom_iframe', 'https://www.naver.com/', true, false, NULL, 10000, 'custom', 'v-platform-template', true, 5, 5, '2026-04-12 12:20:47.07166+00', '2026-04-19 13:31:43.308296+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.notification_app_overrides (id, notification_id, app_id, is_active, updated_at) VALUES (2, 4, 'v-platform-template', false, '2026-04-12 10:39:21.162399+00') ON CONFLICT (notification_id, app_id) DO NOTHING;

SELECT setval('public.menu_items_id_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM public.menu_items), false);
SELECT setval('public.permission_group_grants_id_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM public.permission_group_grants), false);
SELECT setval('public.notification_app_overrides_id_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM public.notification_app_overrides), false);

COMMIT;
