-- Generated by monitoring/scripts/split_seed_dump.py
-- v-ui-builder app baseline seeds (menu_items / grants / overrides scoped to this app).
-- Idempotent: ON CONFLICT DO NOTHING on all inserts.

SET client_encoding = 'UTF8';

BEGIN;

INSERT INTO public.menu_items (id, permission_key, label, icon, path, menu_type, iframe_url, iframe_fullscreen, open_in_new_tab, parent_key, sort_order, section, app_id, is_active, created_by, updated_by, created_at, updated_at) VALUES (2314, 'ui_builder_help', '도움말', 'HelpCircle', '/help', 'built_in', NULL, NULL, NULL, NULL, 700, 'basic', 'v-ui-builder', true, NULL, NULL, '2026-04-19 12:43:55.147737+00', '2026-04-19 12:43:55.147737+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.menu_items (id, permission_key, label, icon, path, menu_type, iframe_url, iframe_fullscreen, open_in_new_tab, parent_key, sort_order, section, app_id, is_active, created_by, updated_by, created_at, updated_at) VALUES (2271, 'ui_builder_sandpack', 'Sandpack 프로젝트', 'Code2', '/', 'built_in', NULL, NULL, NULL, NULL, 100, 'basic', 'v-ui-builder', true, NULL, NULL, '2026-04-19 11:59:53.731799+00', '2026-04-19 11:59:53.731799+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.menu_items (id, permission_key, label, icon, path, menu_type, iframe_url, iframe_fullscreen, open_in_new_tab, parent_key, sort_order, section, app_id, is_active, created_by, updated_by, created_at, updated_at) VALUES (2272, 'ui_builder_genui', 'Generative UI 프로젝트', 'Sparkles', '/genui', 'built_in', NULL, NULL, NULL, NULL, 110, 'basic', 'v-ui-builder', true, NULL, NULL, '2026-04-19 11:59:53.731799+00', '2026-04-19 11:59:53.731799+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.notification_app_overrides (id, notification_id, app_id, is_active, updated_at) VALUES (4, 4, 'v-ui-builder', false, '2026-04-19 04:15:15.269744+00') ON CONFLICT (notification_id, app_id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (6962, 13, 2271, 'write') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (6963, 1, 2271, 'write') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (6964, 2, 2271, 'write') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (6965, 3, 2271, 'read') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (6966, 4, 2271, 'read') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (6967, 14, 2271, 'read') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (6968, 13, 2272, 'write') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (6969, 1, 2272, 'write') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (6970, 2, 2272, 'write') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (6971, 3, 2272, 'read') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (6972, 4, 2272, 'read') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (6973, 14, 2272, 'read') ON CONFLICT (id) DO NOTHING;

SELECT setval('public.menu_items_id_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM public.menu_items), false);
SELECT setval('public.permission_group_grants_id_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM public.permission_group_grants), false);
SELECT setval('public.notification_app_overrides_id_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM public.notification_app_overrides), false);

COMMIT;
