-- Generated by monitoring/scripts/split_seed_dump.py
-- v-channel-bridge app baseline seeds (menu_items / grants / overrides scoped to this app).
-- Idempotent: ON CONFLICT DO NOTHING on all inserts.

SET client_encoding = 'UTF8';

BEGIN;

INSERT INTO public.menu_items (id, permission_key, label, icon, path, menu_type, iframe_url, iframe_fullscreen, open_in_new_tab, parent_key, sort_order, section, app_id, is_active, created_by, updated_by, created_at, updated_at) VALUES (2368, 'dashboard', '대시보드', 'LayoutDashboard', '/', 'built_in', NULL, NULL, NULL, NULL, 100, 'basic', 'v-channel-bridge', true, NULL, NULL, '2026-04-19 13:00:09.897602+00', '2026-04-19 13:00:09.897602+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.menu_items (id, permission_key, label, icon, path, menu_type, iframe_url, iframe_fullscreen, open_in_new_tab, parent_key, sort_order, section, app_id, is_active, created_by, updated_by, created_at, updated_at) VALUES (2369, 'help', '도움말', 'HelpCircle', '/help', 'built_in', NULL, NULL, NULL, NULL, 700, 'basic', 'v-channel-bridge', true, NULL, NULL, '2026-04-19 13:00:09.897602+00', '2026-04-19 13:00:09.897602+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.menu_items (id, permission_key, label, icon, path, menu_type, iframe_url, iframe_fullscreen, open_in_new_tab, parent_key, sort_order, section, app_id, is_active, created_by, updated_by, created_at, updated_at) VALUES (2, 'channels', '채널 관리', 'Radio', '/channels', 'built_in', NULL, NULL, false, NULL, 200, 'basic', 'v-channel-bridge', true, NULL, 5, '2026-04-12 05:15:09.928839+00', '2026-04-12 05:27:19.01844+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.menu_items (id, permission_key, label, icon, path, menu_type, iframe_url, iframe_fullscreen, open_in_new_tab, parent_key, sort_order, section, app_id, is_active, created_by, updated_by, created_at, updated_at) VALUES (5, 'integrations', '연동 관리', 'Link', '/integrations', 'built_in', NULL, NULL, false, NULL, 200, 'basic', 'v-channel-bridge', true, NULL, 5, '2026-04-12 05:15:09.928839+00', '2026-04-12 05:27:19.01844+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.menu_items (id, permission_key, label, icon, path, menu_type, iframe_url, iframe_fullscreen, open_in_new_tab, parent_key, sort_order, section, app_id, is_active, created_by, updated_by, created_at, updated_at) VALUES (3, 'messages', '메시지 히스토리', 'MessageSquare', '/messages', 'built_in', NULL, NULL, false, NULL, 300, 'basic', 'v-channel-bridge', true, NULL, 5, '2026-04-12 05:15:09.928839+00', '2026-04-12 10:57:00.434956+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.menu_items (id, permission_key, label, icon, path, menu_type, iframe_url, iframe_fullscreen, open_in_new_tab, parent_key, sort_order, section, app_id, is_active, created_by, updated_by, created_at, updated_at) VALUES (4, 'statistics', '통계', 'BarChart3', '/statistics', 'built_in', NULL, NULL, false, NULL, 500, 'basic', 'v-channel-bridge', true, NULL, 5, '2026-04-12 05:15:09.928839+00', '2026-04-12 10:57:00.434986+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.notification_app_overrides (id, notification_id, app_id, is_active, updated_at) VALUES (3, 4, 'v-channel-bridge', false, '2026-04-12 13:58:12.368118+00') ON CONFLICT (notification_id, app_id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (28, 1, 2, 'write') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (29, 1, 3, 'write') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (30, 1, 5, 'write') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (33, 1, 4, 'write') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (43, 2, 2, 'write') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (44, 2, 3, 'write') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (45, 2, 5, 'write') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (48, 2, 4, 'write') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (58, 3, 2, 'read') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (59, 3, 3, 'read') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (60, 3, 5, 'read') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (63, 3, 4, 'read') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (65, 4, 2, 'read') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (66, 4, 3, 'read') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (67, 4, 5, 'read') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (70, 4, 4, 'read') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (135, 13, 2, 'write') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (136, 13, 3, 'write') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (137, 13, 4, 'write') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.permission_group_grants (id, permission_group_id, menu_item_id, access_level) VALUES (138, 13, 5, 'write') ON CONFLICT (id) DO NOTHING;

SELECT setval('public.menu_items_id_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM public.menu_items), false);
SELECT setval('public.permission_group_grants_id_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM public.permission_group_grants), false);
SELECT setval('public.notification_app_overrides_id_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM public.notification_app_overrides), false);

COMMIT;
